spring:
  h2:
    console:
      enabled: true
      path: /h2     # Context path
  datasource:
    url: jdbc:h2:mem:test     # JDBC URL
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql # 테이블 생성 파일 경로
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE